version: "3.7"
services:
    discovery-service:
        build:
            context: ./discovery-service
            dockerfile: Dockerfile
        container_name: discovery-service
        image: ami/discovery-service
        environment:
            - port=8761
        ports:
          - "8761:8761"
    gateway-service:
        build:
            context: ./gateway-service
            dockerfile: Dockerfile
        container_name: gateway-service
        image: ami/gateway-service
        environment:
            - port=9999
        ports:
          - "9999:9999"
    dcp-service:
        build:
            context: ./dcp-service
            dockerfile: Dockerfile
        container_name: dcp-service-01
        image: ami/dcp-service
        environment:
            - discoveryServer=discovery-service
            - discoveryPort=8761
            - port=8801
        ports:
          - "8801:8801"
    dcp-validator-service:
        build:
            context: ./dcp-validator-service
            dockerfile: Dockerfile
        container_name: dcp-validator-service-01
        image: ami/dcp-validator-service
        environment:
            - discoveryServer=discovery-service
            - discoveryPort=8761
            - port=8802
        ports:
            - "8802:8802"