server:
  servlet:
    context-path: /ami
spring:
  profiles:
    active: h2
management:
  security:
    enabled: false

---
spring:
  profiles: h2
  datasource:
    platform: h2
    url: jdbc:hsqldb:mem:midas
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: PUBLIC
server.ssl.enabled: false