hystrix.command.fallbackcmd.execution.isolation.thread.timeoutInMilliseconds: 2000
spring:
  application:
    name: gateway-service
server:
  port: ${port}
  servlet:
    context-path: /ami
eureka:
  client:
    serviceUrl:
      defaultZone: http://${discoveryServer}:${discoveryPort}/eureka
  instance:
    preferIpAddress: true
logging:
  level:
    com.netflix.discovery: WARN
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
