spring:
  profiles:
    active: h2
  application:
    name: dcp-validator-service
server:
  port: 8802
  servlet:
    context-path: /ami
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER}:${EUREKA_PORT}/eureka
#  instance:
#    preferIpAddress: true

---
spring:
  profiles: h2
  datasource:
    platform: h2
    url: jdbc:hsqldb:mem:midas
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: PUBLIC
server.ssl.enabled: false